# Build Stage con Maven y Temurin JDK 17
FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime Stage ligero con JRE 17 Alpine
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN addgroup -S bcrp && adduser -S bcrp -G bcrp
USER bcrp
COPY --from=build /app/target/sigir-backend-1.0.0-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Djava.security.egd=file:/dev/./urandom", "app.jar"]
